version: '3.8'

services:
  static_page:
    image: nadavops/nginx:dynamic_env_message_page
    hostname: dynamic_env_message_page
    pull_policy: always
    environment:
        MESSAGE: "static_page"

  echo-server-google:
    image: gcr.io/google-containers/echoserver:1.0
    hostname: echoserver
    pull_policy: always

  oauth-proxy2:
    image: nadavops/oauth-proxy:v7.4.0
    hostname: oauthproxy
    pull_policy: always
    environment:
      OAUTH2_PROXY_UPSTREAM: "http://dynamic_env_message_page:80" # "http://echo-server-google:8080"
      OAUTH2_PROXY_CLIENT_ID: "\$OAUTH_GOOGLE_CLIENT_ID"
      OAUTH2_PROXY_CLIENT_SECRET: "\$OAUTH_GOOGLE_CLIENT_SECRET"
      OAUTH2_PROXY_COOKIE_SECRET: "\$OAUTH_GOOGLE_COOKIE_SECRET"
      OAUTH2_PROXY_COOKIE_REFRESH: "1h"
      OAUTH2_PROXY_COOKIE_EXPIRE: "12h"
      OAUTH2_PROXY_PROVIDER: "google"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_HTTP_ADDRESS: "oauthproxy:4180"
      OAUTH2_PROXY_EMAIL_DOMAINS: "\${OAUTH_PROXY_EMAIL_DOMAINS-*}"
      OAUTH2_PROXY_PASS_HOST_HEADER: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      # OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: "true"

